-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 10:26:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_totalservicos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_totalservicos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_totalservicos` DEFAULT CHARACTER SET utf8 ;
USE `db_totalservicos` ;

-- -----------------------------------------------------
-- Table `db_totalservicos`.`tb_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_totalservicos`.`tb_agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `dt_agendamento` DATE NOT NULL,
  `hr_agendamento` TIME NOT NULL,
  `nm_cliente` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `servico` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_agendamento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
